/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pistacarros;

import clases.Auto;
import clases.Carrera;
import clases.Cronometro;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Zhunio
 */
public class frmPista extends javax.swing.JFrame {

    /**
     * Creates new form frmPista
     */
    public frmPista() {
        initComponents();
        lbCronometro.setVisible(false);
        
        this.setLocationRelativeTo(null);
        this.setTitle("Carrera de Autos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPista = new javax.swing.JPanel();
        auto5 = new javax.swing.JLabel();
        auto1 = new javax.swing.JLabel();
        auto3 = new javax.swing.JLabel();
        auto4 = new javax.swing.JLabel();
        auto2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        lbCronometro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("CARRERA DE AUTOS");

        pnlPista.setBackground(new java.awt.Color(255, 255, 255));
        pnlPista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPista.setOpaque(false);

        auto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quinto.jpeg"))); // NOI18N

        auto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/auto .png"))); // NOI18N

        auto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tercero.jpeg"))); // NOI18N

        auto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuarto.jpeg"))); // NOI18N

        auto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/segundo.png"))); // NOI18N

        javax.swing.GroupLayout pnlPistaLayout = new javax.swing.GroupLayout(pnlPista);
        pnlPista.setLayout(pnlPistaLayout);
        pnlPistaLayout.setHorizontalGroup(
            pnlPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPistaLayout.createSequentialGroup()
                .addGroup(pnlPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(auto4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(auto5)
                    .addComponent(auto3)
                    .addComponent(auto2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1210, Short.MAX_VALUE))
        );
        pnlPistaLayout.setVerticalGroup(
            pnlPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPistaLayout.createSequentialGroup()
                .addComponent(auto1)
                .addGap(59, 59, 59)
                .addComponent(auto2)
                .addGap(63, 63, 63)
                .addComponent(auto3)
                .addGap(60, 60, 60)
                .addComponent(auto4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(auto5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Pausar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnIniciar.setText("Comenzar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lbCronometro.setBackground(new java.awt.Color(0, 0, 0));
        lbCronometro.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        lbCronometro.setForeground(new java.awt.Color(255, 204, 0));
        lbCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCronometro.setText("00:00:00");
        lbCronometro.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lbCronometro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCronometro.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(519, 519, 519))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(315, 315, 315)
                                .addComponent(lbCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(pnlPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(pnlPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        lbCronometro.setVisible(true);
        ArrayList<Auto> participantes = new ArrayList<Auto>(){{
            add(new Auto(auto1));
            add(new Auto(auto2));
            add(new Auto(auto3));
            add(new Auto(auto4));
            add(new Auto(auto5));
            }};
        Cronometro cronometro = new Cronometro(lbCronometro);
        // cronometro.Iniciar();
        Thread carrera = new Thread(new Carrera(participantes, this, cronometro));
        carrera.start();
        
    }//GEN-LAST:event_btnIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel auto1;
    public javax.swing.JLabel auto2;
    private javax.swing.JLabel auto3;
    private javax.swing.JLabel auto4;
    private javax.swing.JLabel auto5;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbCronometro;
    public static javax.swing.JPanel pnlPista;
    // End of variables declaration//GEN-END:variables
}
