package pistacarros;

import clases.Auto;
import java.util.ArrayList;

/**
 *
 * @author Zhunio
 */
public class Podio extends javax.swing.JFrame {

    public Podio(ArrayList<Auto> posiciones) {
        initComponents();
        this.setLocationRelativeTo(null);
        Coronar(posiciones);
    }
    
    public void Coronar(ArrayList<Auto> posiciones) {
        lbPrimero.setIcon(posiciones.get(0).getVehiculo().getIcon());
        lbSegundo.setIcon(posiciones.get(1).getVehiculo().getIcon());
        lbTercero.setIcon(posiciones.get(2).getVehiculo().getIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSegundo = new javax.swing.JLabel();
        lbTercero = new javax.swing.JLabel();
        lbPrimero = new javax.swing.JLabel();
        lbPodio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 140));
        jPanel1.add(lbTercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, 140));
        jPanel1.add(lbPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 140));

        lbPodio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/podio.jpg"))); // NOI18N
        jPanel1.add(lbPodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPodio;
    private javax.swing.JLabel lbPrimero;
    private javax.swing.JLabel lbSegundo;
    private javax.swing.JLabel lbTercero;
    // End of variables declaration//GEN-END:variables
}
